export const MARKET_CATEGORIES = [
  { id: "art", label: "Art" },
  { id: "cars", label: "Cars" },
  { id: "general", label: "General" },
  { id: "homes", label: "Homes" },
  { id: "land", label: "Land" },
  { id: "motorcycles", label: "Motorcycles" },
  { id: "pets", label: "Pets" },
  { id: "rentals", label: "Rentals" },
  { id: "rooms", label: "Rooms" },
  { id: "rvs", label: "RVs" },
  { id: "services", label: "Services" },
  { id: "timeshare", label: "Timeshare" },
  { id: "trucks", label: "Trucks" },
];
