packages:
  - .
  - "functions"
  - "admin"
  - "databaseAdmin"
  - "my-app"

onlyBuiltDependencies:
  - '@firebase/util'
  - bufferutil
  - keccak
  - protobufjs
  - secp256k1
  - sharp
  - utf-8-validate
