// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IERC20 {
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transfer(address to, uint256 amount) external returns (bool);
}

contract BazariaEscrowVault {
    address public bazToken;
    address public serverSigner;
    address public owner;

    // Track used signature hashes to prevent replay attacks
    mapping(bytes32 => bool) public executedSignatures;
    // Track active escrow balances by a unique reference ID
    mapping(bytes32 => uint256) public escrowBalances;

    event Deposited(address indexed user, uint256 amount, bytes32 indexed referenceId);
    event Released(address indexed user, uint256 to, uint256 amount, bytes32 indexed referenceId);
    event SignerUpdated(address indexed oldSigner, address indexed newSigner);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not the contract owner");
        _;
    }

    constructor(address _bazToken, address _serverSigner) {
        require(_bazToken != address(0), "Invalid token address");
        require(_serverSigner != address(0), "Invalid signer address");
        bazToken = _bazToken;
        serverSigner = _serverSigner;
        owner = msg.sender;
    }

    /**
     * @notice Locks BAZ tokens into the escrow vault for a specific transaction/order.
     * @param amount The volume of BAZ tokens to lock (requires prior ERC20 allowance approval).
     * @param referenceId A unique bytes32 hash tracking this specific order or item context.
     */
    function depositTokens(uint256 amount, bytes32 referenceId) external {
        require(amount > 0, "Amount must be greater than zero");
        require(referenceId != bytes32(0), "Invalid reference ID");
        require(escrowBalances[referenceId] == 0, "Reference ID already exists");

        // Transfer tokens from the user into this contract vault
        bool success = IERC20(bazToken).transferFrom(msg.sender, address(this), amount);
        require(success, "Token transfer failed");

        escrowBalances[referenceId] = amount;

        emit Deposited(msg.sender, amount, referenceId);
    }

    /**
     * @notice Releases tokens from a specific escrow pool to a recipient using a server signature authorization voucher.
     * @param recipient The target wallet address receiving the released funds.
     * @param amount The specific amount to release.
     * @param referenceId The tracking identifier of the escrow source pool.
     * @param signature The ECDSA cryptographic signature generated by the backend serverSigner.
     */
    function releaseTokens(
        address recipient,
        uint256 amount,
        bytes32 referenceId,
        bytes calldata signature
    ) external {
        require(recipient != address(0), "Invalid recipient address");
        require(amount > 0, "Amount must be greater than zero");
        require(escrowBalances[referenceId] >= amount, "Insufficient escrow balance");

        // 1. Recreate the precise message hash that the server signed off-chain
        bytes32 messageHash = keccak256(abi.encodePacked(recipient, amount, referenceId, address(this)));
        bytes32 ethSignedMessageHash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash));

        // 2. Prevent the exact same signature voucher from being re-used/replayed
        require(!executedSignatures[ethSignedMessageHash], "Signature already executed");
        executedSignatures[ethSignedMessageHash] = true;

        // 3. Recover the signer address from the signature and verify it matches our serverSigner
        address recoveredSigner = recoverSigner(ethSignedMessageHash, signature);
        require(recoveredSigner == serverSigner, "Invalid server signature authorization");

        // 4. Update state and transfer out the vault funds
        escrowBalances[referenceId] -= amount;
        bool success = IERC20(bazToken).transfer(recipient, amount);
        require(success, "Token payout failed");

       emit Released(recipient, recipient, amount, referenceId);
    }

    /**
     * @notice Administrative function to update the server's public key identifier if needed.
     */
    function updateServerSigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid signer address");
        emit SignerUpdated(serverSigner, _newSigner);
        serverSigner = _newSigner;
    }

    /**
     * @dev Internal helper function to extract the signer address via ecrecover
     */
    function recoverSigner(bytes32 _ethSignedMessageHash, bytes memory _signature) internal pure returns (address) {
        require(_signature.length == 65, "Invalid signature length");

        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := mload(add(_signature, 32))
            s := mload(add(_signature, 64))
            v := byte(0, mload(add(_signature, 96)))
        }

        return ecrecover(_ethSignedMessageHash, v, r, s);
    }
}
